### ISSUE TITLE
Responses for "What about all those papers I published before I knew about the Open Access movement? The license prohibits me from posting them now. What can I do?"

### ISSUE THREAD

**Issue by parnopaeus** [KirstieJane/OpenAdvice#4]
Here are some things that you can do:

- You may be able to archive a pre-print or post-print, depending on the journal's license. Search for the journal's name in [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/), which will tell you what you are allowed to self-archive. If you kept a version of your paper - either the draft that you submitted to the journal for consideration (preprint) or the revised version that you did after peer review (postprint), you may be able to archive these in an institutional repository or a disciplinary repository. 

- You can always write to the journal and ask. This request can also apply to book chapters and other non-journal publications. Here is a template for an e-mail to request this permission (borrowed from the [University of Toronto](https://tspace.library.utoronto.ca/bitstream/1807/68610/1/Self-Archiving%20Permission.pdf)):

> 
> Dear permissions contact,
> 
> I write to request permission to self-archive my article, “[article citation]” in my [institutional repository/disciplinary repository], [name of repository]. I would be happy to acknowledge your publication and/or copyright in the description.
> 
> Thank you for your time. I look forward to hearing back from you regarding permission to
> make this article available on [repository name].
> Sincerely,
> [Name] 
> 

- Make sure to archive all of your work going forward. Check the journal on SHERPA/RoMEO(http://www.sherpa.ac.uk/romeo/) first, then archive as soon as you are accepted for publication!

**Comment by KirstieJane** [comment]
ON THE [SITE](https://kirstiejane.github.io/OpenAdvice/#questions)! Thank you @parnopaeus
