### ISSUE TITLE
Response for "My boss is determined to publish in a paywalled jounal. Is there anything I can do to make my paper available?"

### ISSUE THREAD

**Issue by parnopaeus** [KirstieJane/OpenAdvice#5]
Please discuss self-archiving with your boss! Most reputable journals allow for the self-archiving of postprints or preprints in repositories. Search [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/index.php) for the journal title and see what the journal allows for self-archiving. Explain the [benefits](http://f1000research.com/articles/5-632/v3) of making a version of the article Open Access, which includes potentially increased citations and attention for your paper as well as providing access to a version of your results for those who do not have subscriptions to the journal. These benefits can be particularly helpful for Early Career Researchers and increased attention can help you advance your career (which will make your boss look good too) while still adhering to your boss's requirement to publish in the paywalled journal.

**Comment by daniellecrobinson** [comment]
Perfect!

**Comment by KirstieJane** [comment]
[On the site](https://kirstiejane.github.io/OpenAdvice/#questions)! Thank you @parnopaeus!

Added the benefits link to the [resources session](https://kirstiejane.github.io/OpenAdvice/#resources)!
